CREATE TABLE `FOITHTHS` (
	`AM` int(255) NOT NULL,
	`ONOMA` varchar(255) NOT NULL,
	`THLEFONO` int(10) NOT NULL,
	PRIMARY KEY (`AM`)
);

CREATE TABLE `KARTA_SITHSHS` (
	`ID_CARD` INT NOT NULL UNIQUE,
	`HM_ARXHS` DATE NOT NULL,
	`HM_TELOUS` DATE NOT NULL,
	PRIMARY KEY (`ID_CARD`)
);

CREATE TABLE `ESTIA` (
	`TOPOTHESIA` varchar(255) NOT NULL,
	`ONOMA` varchar(255) NOT NULL,
	`ID_DOMATIOU` INT NOT NULL UNIQUE,
	PRIMARY KEY (`TOPOTHESIA`,`ID_DOMATIOU`)
);

CREATE TABLE `AITHSH_SITHSHS` (
	`ID` INT NOT NULL,
	`AM` INT NOT NULL,
	`AK_ETOS_EGGRAFHS` year NOT NULL,
	`D/NSH_KATOIKIAS` varchar(255) NOT NULL,
	`D/NSH_MONIMHS_KATOIKIAS` varchar(255) NOT NULL,
	`BARCODE_PASOU` int(255) NOT NULL,
	`SYNOLIKO_EISODHMA_PATROS` varchar(255) NOT NULL,
	`SYNOLIKO_EISODHMA_MHTROS` varchar(255) NOT NULL,
	`AR_MELON_OIKOGENEIAS` int(255) NOT NULL,
	PRIMARY KEY (`ID`,`AM`)
	CONSTRAINT `AITHSH_SITHSHS_fk0`
	FOREIGN KEY (`ID`) REFERENCES `KANEI_AITHSH`(`ID`)
	CONSTRAINT `AITHSH_SITHSHS_fk1` 
	FOREIGN KEY (`AM`) REFERENCES `KANEI_AITHSH`(`AM`)
);

CREATE TABLE `AITHSH_STEGASHS` (
	`ID` INT NOT NULL,
	`AM` INT NOT NULL,
	`KATHGORIA` varchar(255) NOT NULL,
	`D/NSH_MONIMHS_KATOIKIAS` varchar(255) NOT NULL,
	`THL_GONEON` varchar(255) NOT NULL,
	`EPAGGELMA_PATROS` varchar(255) NOT NULL,
	`EPAGGELNA_MHTROS` varchar(255) NOT NULL,
	`TOPOTHESIA_TMHMATOS` varchar(255) NOT NULL,
	`SYNOLIKO_EISODHMA_PATROS` varchar(255) NOT NULL,
	`SYNOLIKO_EISODHMA_MHTROS` varchar(255) NOT NULL,
	`SYNOLIKO_EISODHMA_IDIOU` varchar(255) NOT NULL,
	`AR_MELON_OIKOGENEIAS` int(255) NOT NULL,
	`ADELFIA_POU_SPOUDAZOYN` varchar(255) NOT NULL,
	`GONEIS_ME_EIDIKES_ANAGKES` varchar(255) NOT NULL,
	`DIAZEUGMENOI_GONEIS` varchar(255) NOT NULL,
	`ORFANOS_APO_ENAN_GONEA` varchar(255) NOT NULL,
	`POLUTEKNH_OIKOGENEIA` varchar(255) NOT NULL,
	`STRATIOTIKH_THHTEIA_ADELFOU` varchar(255) NOT NULL,
	`MELH_OIKOGENEIAS_ME_EIDIKES_ANAGKES` varchar(255) NOT NULL,
	PRIMARY KEY (`ID`,`AM`)
	CONSTRAINT `AITHSH_STEGASHS_fk0` 
	FOREIGN KEY (`ID`) 
	REFERENCES `KANEI_AITHSH`(`ID`)

	CONSTRAINT `AITHSH_STEGASHS_fk1` 
	FOREIGN KEY (`AM`) 
	REFERENCES `KANEI_AITHSH`(`AM`)
);

CREATE TABLE `DOMATIA` (
	`ID_DOMATIOU` INT(255) NOT NULL UNIQUE,
	`OROFOS` int NOT NULL,
	`ARITHMOS` int NOT NULL,
	`PTERYGA` varchar(255) NOT NULL,
	PRIMARY KEY (`ID_DOMATIOU`)
	CONSTRAINT `DOMATIA_fk0` 
	FOREIGN KEY (`ID_DOMATIOU`) 
	REFERENCES `ESTIA`(`ID_DOMATIOU`)
);

CREATE TABLE `DIAMENEI` (
	`AM` INT NOT NULL,
	`ID_DOMATIOU` INT NOT NULL,
	`HM_ARXHS` DATE NOT NULL,
	`HM_TELOUS` DATE NOT NULL,
	PRIMARY KEY (`AM`)
	CONSTRAINT `DIAMENEI_fk0` 
	FOREIGN KEY (`AM`) 
	REFERENCES `AITHSH_STEGASHS`(`AM`)

	CONSTRAINT `DIAMENEI_fk1` 
	FOREIGN KEY (`ID_DOMATIOU`) 
	REFERENCES `DOMATIA`(`ID_DOMATIOU`)

);

CREATE TABLE `LAMVANEI` (
	`AM` INT NOT NULL,
	`ID_CARD` INT NOT NULL,
	PRIMARY KEY (`AM`,`ID_CARD`)
	CONSTRAINT `LAMVANEI_fk0` 
	FOREIGN KEY (`AM`) 
	REFERENCES `AITHSH_SITHSHS`(`AM`)

	CONSTRAINT `LAMVANEI_fk1` 
	FOREIGN KEY (`ID_CARD`) 
	REFERENCES `KARTA_SITHSHS`(`ID_CARD`)

);

CREATE TABLE `AGORA_KOUPONION` (
	`ID` INT NOT NULL,
	`AM` INT NOT NULL,
	`HM_AGORAS` DATE NOT NULL,
	`POSOTHTA` INT NOT NULL,
	`TIMH` INT NOT NULL,
	PRIMARY KEY (`ID`,`AM`)
	CONSTRAINT `AGORA_KOUPONION_fk0` 
	FOREIGN KEY (`AM`) 
	REFERENCES `FOITHTHS`(`AM`)
);

CREATE TABLE `EGGRAFA` (
	`ID_AITHSHS` INT NOT NULL,
	`ONOMA` varchar NOT NULL,
	PRIMARY KEY (`ID_AITHSHS` , `ONOMA`)

	CONSTRAINT `EGGRAPHA_fk0` 
	FOREIGN KEY (`ID_AITHSHS`) 
	REFERENCES `KANEI_AITHSH`(`ID`)
);

CREATE TABLE `KANEI_AITHSH` (
	`ID` INT NOT NULL,
	`AM` INT NOT NULL,
	`HM` varchar(255) NOT NULL,
	`KATASTASH` varchar(255) NOT NULL,
	`EIDOS_AITHSHS` varchar(255) NOT NULL,
	PRIMARY KEY (`ID`,`AM`)
	CONSTRAINT `KANEI_AITHSH_fk0` 
	FOREIGN KEY (`AM`) 
	REFERENCES `FOITHTHS`(`AM`)
);

















