DROP TABLE IF EXISTS FOITHTHS;
CREATE TABLE IF NOT EXISTS FOITHTHS 
(
    AM INTEGER NOT NULL,
    ONOMA varchar NOT NULL,
    THLEFONO INTEGER NOT NULL,
    PRIMARY key (AM)
);

DROP TABLE IF EXISTS KARTA_SITHSHS;
CREATE TABLE IF NOT EXISTS KARTA_SITHSHS 
(
    ID_CARD INTEGER NOT NULL,
    HM_ARXHS DATE NOT NULL,
    HM_TELOUS DATE NOT NULL,
    PRIMARY key (ID_CARD)
);

DROP TABLE IF EXISTS ESTIA;
CREATE TABLE IF NOT EXISTS ESTIA
(
	TOPOTHESIA varchar(255) NOT NULL,
	ONOMA varchar(255) NOT NULL,
	ID_DOMATIOU INTEGER NOT NULL,
	PRIMARY KEY (TOPOTHESIA,ID_DOMATIOU)
);

DROP TABLE IF EXISTS AITHSH_SITHSHS;
CREATE TABLE IF NOT EXISTS AITHSH_SITHSHS 
(
	ID INTEGER NOT NULL,
	AM INTEGER NOT NULL,
	AK_ETOS_EGGRAFHS year NOT NULL,
	'D/NSH_KATOIKIAS' varchar(255) NOT NULL,
	'D/NSH_MONIMHS_KATOIKIAS' varchar(255) NOT NULL,
	BARCODE_PASOU INTEGER NOT NULL,
	SYNOLIKO_EISODHMA_PATROS varchar(255) NOT NULL,
	SYNOLIKO_EISODHMA_MHTROS varchar(255) NOT NULL,
	AR_MELON_OIKOGENEIAS int(255) NOT NULL,
	FOREIGN KEY (ID , AM) 
	REFERENCES KANEI_AITHSH(ID , AM)
    ON DELETE CASCADE
);

DROP TABLE IF EXISTS AITHSH_STEGASHS;
CREATE TABLE IF NOT EXISTS AITHSH_STEGASHS 
(
	ID INTEGER NOT NULL,
	AM INTEGER NOT NULL,
	KATHGORIA varchar(255) NOT NULL,
	'D/NSH_MONIMHS_KATOIKIAS' varchar(255) NOT NULL,
	THL_GONEON varchar(255) NOT NULL,
	EPAGGELMA_PATROS varchar(255) NOT NULL,
	EPAGGELNA_MHTROS varchar(255) NOT NULL,
	TOPOTHESIA_TMHMATOS varchar(255) NOT NULL,
	SYNOLIKO_EISODHMA_PATROS varchar(255) NOT NULL,
	SYNOLIKO_EISODHMA_MHTROS varchar(255) NOT NULL,
	SYNOLIKO_EISODHMA_IDIOU varchar(255) NOT NULL,
	AR_MELON_OIKOGENEIAS INTEGER(255) NOT NULL,
	ADELFIA_POU_SPOUDAZOYN varchar(255) NOT NULL,
	GONEIS_ME_EIDIKES_ANAGKES varchar(255) NOT NULL,
	DIAZEUGMENOI_GONEIS varchar(255) NOT NULL,
	ORFANOS_APO_ENAN_GONEA varchar(255) NOT NULL,
	POLUTEKNH_OIKOGENEIA varchar(255) NOT NULL,
	STRATIOTIKH_THHTEIA_ADELFOU varchar(255) NOT NULL,
	MELH_OIKOGENEIAS_ME_EIDIKES_ANAGKES varchar(255) NOT NULL,

	FOREIGN KEY (ID,AM) 
	REFERENCES KANEI_AITHSH(ID,AM) 
    ON DELETE CASCADE
);

DROP TABLE IF EXISTS DOMATIA;
CREATE TABLE IF NOT EXISTS DOMATIA
(
	ID_DOMATIOU INTEGER NOT NULL,
	OROFOS INTEGER NOT NULL,
	ARITHMOS INTEGER NOT NULL,
	FOREIGN KEY (ID_DOMATIOU) 
	REFERENCES ESTIA(ID_DOMATIOU) 
    ON DELETE CASCADE
);

DROP TABLE IF EXISTS DIAMENEI;
CREATE TABLE IF NOT EXISTS DIAMENEI
(
	AM INTEGER NOT NULL,
	ID_DOMATIOU INTEGER NOT NULL,
	HM_ARXHS DATE NOT NULL,
	HM_TELOUS DATE NOT NULL,
	
	FOREIGN KEY (AM) 
	REFERENCES AITHSH_STEGASHS(AM)
    ON DELETE CASCADE,

	FOREIGN KEY (ID_DOMATIOU) 
	REFERENCES DOMATIA(ID_DOMATIOU)
    ON DELETE CASCADE
);

DROP TABLE IF EXISTS LAMVANEI;
CREATE TABLE IF NOT EXISTS LAMVANEI
(
	AM INTEGER NOT NULL,
	ID_CARD INT NOT NULL,

	FOREIGN KEY (AM) 
	REFERENCES AITHSH_SITHSHS(AM)
    ON DELETE CASCADE,

	FOREIGN KEY (ID_CARD) 
	REFERENCES KARTA_SITHSHS(ID_CARD)
    ON DELETE CASCADE
);

DROP TABLE IF EXISTS AGORA_KOUPONION;
CREATE TABLE IF NOT EXISTS AGORA_KOUPONION
(
	ID INTEGER NOT NULL,
	AM INTEGER NOT NULL,
	HM_AGORAS DATETIME NOT NULL,
	POSOTHTA INTEGER NOT NULL,
	TIMH INTEGER NOT NULL,
	PRIMARY KEY (ID),
    FOREIGN KEY (AM) 
	REFERENCES FOITHTHS(AM)
    ON DELETE CASCADE
);

DROP TABLE IF EXISTS EGGRAFA;
CREATE TABLE IF NOT EXISTS EGGRAFA
(
    ID_AITHSHS INTEGER NOT NULL,
    ONOMA varchar NOT NULL,
	PRIMARY key(ID_AITHSHS, ONOMA),
    FOREIGN key(ID_AITHSHS) 
	REFERENCES KANEI_AITHSH(ID)
    ON DELETE CASCADE
);

DROP TABLE IF EXISTS KANEI_AITHSH;
CREATE TABLE IF NOT EXISTS KANEI_AITHSH
(
    ID INTEGER NOT NULL,
    AM INTEGER NOT NULL,
    HM varchar NOT NULL,
    KATASTASH varchar NOT NULL,
    EIDOS_AITHSHS varchar NOT NULL,
    PRIMARY key (ID),
    FOREIGN KEY (AM) REFERENCES FOITHTHS(AM)
    ON DELETE CASCADE
);

